Power X1 i-CT/Pages/Setup/RobotToTrayUnloader/SetupRobotToTrayUnloader.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Power_X1_iCT.Model;
using Power_X1_iCT.Resources;
using RobotToTrayUnloader.Updater;

namespace Power_X1_iCT.Pages.Setup
{
    [BindProperties]
    public class SetupRobotToTrayUnloaderModel : PageModel
    {
        private readonly ILogger mLog;
        private readonly RobotToTrayUnloaderUpdater mUpdater;

        private RobotToTrayUnloader.Application.RobotToTrayUnloader mRobotToTrayUnloader = RobotToTrayUnloader.Application.RobotToTrayUnloader.Instance;

        public RobotToTrayUnloaderSettingsModel RobotToTrayUnloaderSettingsModel { get; set; }
        public InspectionSettingsModel InspectionSettingsModel { get; set; }
        public bool SimulationEnabled { get; set; }
        public bool IsRunningProduction { get; set; }
        public RobotSettingsModel RobotSettingsModel { get; set; } 
        public RobotPickSettingsModel RobotPickSettingsModel { get; set; }
        public RobotPlaceSettingsModel RobotPlaceSettingsModel { get; set; } 
        public RobotHomeSettingsModel RobotHomeSettingsModel { get; set; } 

        public SetupRobotToTrayUnloaderModel(RobotToTrayUnloaderUpdater robotToTrayUnloaderUpdater, ILogger<SetupRobotToTrayUnloaderModel> logger)
        {
            mLog = logger;
            mUpdater = robotToTrayUnloaderUpdater;
            RobotToTrayUnloaderSettingsModel = new RobotToTrayUnloaderSettingsModel();
            InspectionSettingsModel = new InspectionSettingsModel();
            RobotSettingsModel = new RobotSettingsModel();
            RobotPickSettingsModel = new RobotPickSettingsModel();
            RobotPlaceSettingsModel = new RobotPlaceSettingsModel();
            RobotHomeSettingsModel = new RobotHomeSettingsModel();
        }
        public JsonResult OnPostGetState()
        {
            return new JsonResult(new { state = StateBar.ConvertToString(mRobotToTrayUnloader.State) });
        }

        public JsonResult OnPostGetStatusses()
        {
            return mUpdater.GetStatusses();
        }

        public JsonResult OnPostGetSimulationEnabled()
        {
            return new JsonResult(mRobotToTrayUnloader.InSimulation);
        }

        public void OnPostInitialize()
        {
            mLog.LogInformation("OnInitialize");
            mRobotToTrayUnloader.Initialize();
        }

        public void OnPostStart()
        {
            mLog.LogInformation("OnStart");
            mRobotToTrayUnloader.Start();
        }

        public void OnPostStop()
        {
            mLog.LogInformation("OnStop");
            mRobotToTrayUnloader.Stop();
        }

        public void OnPostInspectionCommand()
        {
            mLog.LogInformation("OnInspection");
            mRobotToTrayUnloader.Inspect();
        }

        public void OnPostToInfeedCommand()
        {
            mLog.LogInformation("OnInfeed");
            mRobotToTrayUnloader.InspectToInfeed();
        }

        public void OnPostRobotPickCommand()
        {
            mLog.LogInformation("OnPick");
            mRobotToTrayUnloader.Pick();
        }
        public void OnPostRobotPlaceCommand()
        {
            mLog.LogInformation("OnPick");
            mRobotToTrayUnloader.Place();
        }
        public void OnPostRobotHomeCommand()
        {
            mLog.LogInformation("OnHome");
            mRobotToTrayUnloader.Home();
        }

        public void OnPostDownloadInspectionSettingsToPLC(InspectionSettingsModel model)
        {
            model.Download();
        }

        public void OnPostSaveInspectionSettings(InspectionSettingsModel model)
        {
            model.Save();
        }

        public void OnPostDownloadRobotSettingsToPLC(RobotSettingsModel model)
        {
            model.Download();
        }

        public void OnPostSaveRobotSettings(RobotSettingsModel model)
        {
            model.Save();
        }

        public void OnPostDownloadRobotPickSettingsToPLC(RobotPickSettingsModel model)
        {
            model.Download();
        }

        public void OnPostSaveRobotPickSettings(RobotPickSettingsModel model)
        {
            model.Save();
        }

        public void OnPostDownloadRobotPlaceSettingsToPLC(RobotPlaceSettingsModel model)
        {
            model.Download();
        }

        public void OnPostSaveRobotPlaceSettings(RobotPlaceSettingsModel model)
        {
            model.Save();
        }

        public void OnPostDownloadRobotHomeSettingsToPLC(RobotHomeSettingsModel model)
        {
            model.Download();
        }

        public void OnPostSaveRobotHomeSettings(RobotHomeSettingsModel model)
        {
            model.Save();   
        }

        public void OnPostSimulationChanged()
        {
            if (SimulationEnabled)
            {
                mRobotToTrayUnloader.DisableSimulation();
            }
            else
            {
                mRobotToTrayUnloader.EnableSimulation();
            }
        }
        public ActionResult OnPostSetVelocityPercentage(int percentage)
        {
            RobotToTrayUnloaderSettingsModel.SetVelocityPercentage(percentage);

            return new JsonResult("Succes");
        }
    }
}

Power X1 i-CT/Pages/Setup/RobotToTrayUnloader/Subprocesses/InspectionSettingsPartial.cshtml
<form method="post">
    <button class="button" id="CloseSetupInspection" title="Close settings" style="float:right; width:50px; height:50px">
        <img src="~/icons/close.png" style="width:35px; padding:1px" />
    </button>
</form>
<form method="post">
    <h2>Inspection settings</h2>
    <div>&nbsp;</div>
    <div class="settings-card">
        <div class="row">
            <label for="InfeedPosition" class="col-5">Infeed position</label>
            <input class="textbox" id="InfeedPosition" name="InfeedPosition" type="number" value="@Model.InspectionSettingsModel.InfeedPosition.ToString("F2")" min="1.00" max="300.00" step="0.10" />
            <label for="InfeedPosition">mm</label>
        </div>
        <div class="row">
            <label for="OutfeedPosition" class="col-5">Outfeed position </label>
            <input class="textbox" id="OutfeedPosition" name="OutfeedPosition" type="number" value="@Model.InspectionSettingsModel.OutfeedPosition.ToString("F2")" min="1.00" max="500.00" step="0.10" />
            <label for="OutfeedPosition">mm</label>
        </div>
        <div class="row">
            <label for="StartInspectionPosition" class="col-5">Start inspection position</label>
            <input class="textbox" id="StartInspectionPosition" name="StartInspectionPosition" type="number" value="@Model.InspectionSettingsModel.StartInspectionPosition.ToString("F2")" min="1.00" max="500.00" step="0.1" />
            <label for="StartInspectionPosition">mm</label>
        </div>
        <div class="row">
            <label for="Velocity" class="col-5">Velocity</label>
            <input class="textbox" id="Velocity" name="Velocity" type="number" value="@Model.InspectionSettingsModel.Velocity" min="10" max="100" step="5" />
            <label for="Velocity">%</label>
        </div>              
    </div>
    <div>&nbsp;</div>
    <div class="text-center">
        <button class="button" asp-page-handler="DownloadInspectionSettingsToPLC" title="Download to PLC">
            <img src="~/icons/download.png" width="30">
        </button>
        <button class="button" asp-page-handler="SaveInspectionSettings" title="Save to database">
            <img src="~/icons/save.png" width="30">
        </button>
        <button class="button" asp-page-handler="RefreshInspectionSettingsFromRecipe" title="Load from database">
            <img src="~/icons/back.png" width="30">
        </button>
    </div>
</form>

Power X1 i-CT/Pages/Setup/RobotToTrayUnloader/Subprocesses/RobotHomeSettingsPartial.cshtml
<form method="post">
    <button class="button" id="CloseSetupRobotHome" title="Close settings" style="float:right; width:50px; height:50px">
        <img src="~/icons/close.png" style="width:35px; padding:1px" />
    </button>
</form>
<form method="post">
    <h2>Robot home settings</h2>
    <div>&nbsp;</div>
    <div class="settings-card">
        <div class="row">
            <label for="PositionX" class="col-5">Position X</label>
            <input class="textbox" id="HomePositionX" name="PositionX" type="number" value="@Model.RobotHomeSettingsModel.PositionX.ToString("F2")" min="1.00" max="1025.00" step="0.10" />
            <label for="PositionX">mm</label>
        </div>
        <div class="row">
            <label for="PositionY" class="col-5">Position Y </label>
            <input class="textbox" id="HomePositionY" name="PositionY" type="number" value="@Model.RobotHomeSettingsModel.PositionY.ToString("F2")" min="1.00" max="25.00" step="0.1" />
            <label for="PositionY">mm</label>
        </div>
        <div class="row">
            <label for="PositionZ" class="col-5">Position Z</label>
            <input class="textbox" id="HomePositionZ" name="PositionZ" type="number" value="@Model.RobotHomeSettingsModel.PositionZ.ToString("F2")" min="1.00" max="225.00" step="0.1" />
            <label for="PositionZ">mm</label>
        </div>
        <div class="row">
            <label for="PositionR" class="col-5">Position R</label>
            <input class="textbox" id="HomePositionR" name="PositionR" type="number" value="@Model.RobotHomeSettingsModel.PositionR.ToString("F2")" min="-180" max="270" step="90" />
            <label for="PositionR">deg</label>
        </div>
    </div>
    <div>&nbsp;</div>
    <div class="text-center">
        <button class="button" asp-page-handler="DownloadRobotHomeSettingsToPLC" title="Download to PLC">
            <img src="~/icons/download.png" width="30">
        </button>
        <button class="button" asp-page-handler="SaveRobotHomeSettings" title="Save to database">
            <img src="~/icons/save.png" width="30">
        </button>
        <button class="button" asp-page-handler="RefreshRobotHomeSettingsFromRecipe" title="Load from database">
            <img src="~/icons/back.png" width="30">
        </button>
    </div>
</form>

Power X1 i-CT/Pages/Setup/RobotToTrayUnloader/Subprocesses/RobotPickSettingsPartial.cshtml
<form method="post">
    <button class="button" id="CloseSetupRobotPick" title="Close settings" style="float:right; width:50px; height:50px">
        <img src="~/icons/close.png" style="width:35px; padding:1px" />
    </button>
</form>
<form method="post">
    <h2>Robot pick settings</h2>
    <div>&nbsp;</div>
    <div class="settings-card">
        <div class="row">
            <label for="PickPositionX" class="col-5">Position X</label>
            <input class="textbox" id="PickPositionX" name="PositionX" type="number" value="@Model.RobotPickSettingsModel.PositionX.ToString("F2")" min="1.00" max="1025.00" step="0.10" />
            <label for="PickPositionX">mm</label>
        </div>
        <div class="row">
            <label for="PickPositionY" class="col-5">Position Y </label>
            <input class="textbox" id="PickPositionY" name="PositionY" type="number" value="@Model.RobotPickSettingsModel.PositionY.ToString("F2")" min="1.00" max="25.00" step="0.1" />
            <label for="PickPositionY">mm</label>
        </div>
        <div class="row">
            <label for="PickPositionZ" class="col-5">Position Z</label>
            <input class="textbox" id="PickPositionZ" name="PositionZ" type="number" value="@Model.RobotPickSettingsModel.PositionZ.ToString("F2")" min="1.00" max="225.00" step="0.1" />
            <label for="PickPositionZ">mm</label>
        </div>
        <div class="row">
            <label for="PickPositionR" class="col-5">Position R</label>
            <input class="textbox" id="PickPositionR" name="PositionR" type="number" value="@Model.RobotPickSettingsModel.PositionR.ToString("F0")" min="-180" max="270" step="90" />
            <label for="PickPositionR">deg</label>
        </div>
        <div class="row">
            <label for="PickOffsetZ" class="col-5">Offset Z</label>
            <input class="textbox" id="PickOffsetZ" name="PickOffsetZ" type="number" value="@Model.RobotPickSettingsModel.PickOffsetZ.ToString("F2")" min="1.00" max="225.00" step="0.1" />
            <label for="PickOffsetZ">mm</label>
        </div>
        <div class="row">
            <label for="PickApproachVelocityPercentage" class="col-5">Approach velocity percentage</label>
            <input class="textbox" id="PickApproachVelocityPercentage" name="PickApproachVelocityPercentage" type="number" value="@Model.RobotPickSettingsModel.PickApproachVelocityPercentage.ToString("F0")" min="10" max="100" step="5" />
            <label for="PickApproachVelocityPercentage">%</label>
        </div>
        <div class="row">
            <label for="PickClearVelocityPercentage" class="col-5">Clear velocity percentage</label>
            <input class="textbox" id="PickClearVelocityPercentage" name="PickClearVelocityPercentage" type="number" value="@Model.RobotPickSettingsModel.PickClearVelocityPercentage.ToString("F0")" min="10" max="100" step="5" />
            <label for="PickClearVelocityPercentage">%</label>
        </div>

    </div>
    <div>&nbsp;</div>
    <div class="text-center">
        <button class="button" asp-page-handler="DownloadRobotPickSettingsToPLC" title="Download to PLC">
            <img src="~/icons/download.png" width="30">
        </button>
        <button class="button" asp-page-handler="SaveRobotPickSettings" title="Save to database">
            <img src="~/icons/save.png" width="30">
        </button>
        <button class="button" asp-page-handler="RefreshRobotPickSettingsFromRecipe" title="Load from database">
            <img src="~/icons/back.png" width="30">
        </button>
    </div>
</form>

Power X1 i-CT/Pages/Setup/RobotToTrayUnloader/Subprocesses/RobotPlaceSettingsPartial.cshtml
<form method="post">
    <button class="button" id="CloseSetupRobotPlace" title="Close settings" style="float:right; width:50px; height:50px">
        <img src="~/icons/close.png" style="width:35px; padding:1px" />
    </button>
</form>
<form method="post">
    <h2>Robot place settings</h2>
    <div>&nbsp;</div>
    <div class="settings-card">
        <div class="row">
            <label for="PlaceOffsetZ" class="col-5">Offset Z</label>
            <input class="textbox" id="PlaceOffsetZ" name="PlaceOffsetZ" type="number" value="@Model.RobotPlaceSettingsModel.PlaceOffsetZ.ToString("F2")" min="1.00" max="225.00" step="0.1" />
            <label for="PlaceOffsetZ">mm</label>
        </div>
        <div class="row">
            <label for="PlaceApproachVelocityPercentage" class="col-5">Approach velocity percentage</label>
            <input class="textbox" id="PlaceApproachVelocityPercentage" name="PlaceApproachVelocityPercentage" type="number" value="@Model.RobotPlaceSettingsModel.PlaceApproachVelocityPercentage.ToString("F0")" min="10" max="100" step="5" />
            <label for="PlaceApproachVelocityPercentage">%</label>
        </div>
        <div class="row">
            <label for="PlaceClearVelocityPercentage" class="col-5">Clear velocity percentage</label>
            <input class="textbox" id="PlaceClearVelocityPercentage" name="PlaceClearVelocityPercentage" type="number" value="@Model.RobotPlaceSettingsModel.PlaceClearVelocityPercentage.ToString("F0")" min="10" max="100" step="5" />
            <label for="PlaceClearVelocityPercentage">%</label>
        </div>

    </div>
    <div>&nbsp;</div>
    <div class="text-center">
        <button class="button" asp-page-handler="DownloadRobotPlaceSettingsToPLC" title="Download to PLC">
            <img src="~/icons/download.png" width="30">
        </button>
        <button class="button" asp-page-handler="SaveRobotPlaceSettings" title="Save to database">
            <img src="~/icons/save.png" width="30">
        </button>
        <button class="button" asp-page-handler="RefreshRobotPlaceSettingsFromRecipe" title="Load from database">
            <img src="~/icons/back.png" width="30">
        </button>
    </div>
</form>

Power X1 i-CT/Pages/Setup/RobotToTrayUnloader/Subprocesses/RobotSettingsPartial.cshtml
<form method="post">
    <button class="button" id="CloseSetupRobot" title="Close settings" style="float:right; width:50px; height:50px">
        <img src="~/icons/close.png" style="width:35px; padding:1px" />
    </button>
</form>
<form method="post">
    <h2>Robot settings</h2>
    <div>&nbsp;</div>
    <div class="settings-card">
        <div class="row">
            <label for="BaseCount" class="col-5">Base count</label>
            <input class="textbox" id="BaseCount" name="BaseCount" type="number" value="@Model.RobotSettingsModel.BaseCount.ToString("F0")" min="1" max="8" step="1" />
            <label for="BaseCount">#</label>
        </div>
        <div class="row">
            <label for="DefaultVelocityPercentag" class="col-5">Default velocity percentage </label>
            <input class="textbox" id="DefaultVelocityPercentag" name="DefaultVelocityPercentage" type="number" value="@Model.RobotSettingsModel.DefaultVelocityPercentage.ToString("F0")" min="10" max="100" step="5" />
            <label for="DefaultVelocityPercentag">%</label>
        </div>
       
    </div>
    <div>&nbsp;</div>
    <div class="text-center">
        <button class="button" asp-page-handler="DownloadRobotSettingsToPLC" title="Download to PLC">
            <img src="~/icons/download.png" width="30">
        </button>
        <button class="button" asp-page-handler="SaveRobotSettings" title="Save to database">
            <img src="~/icons/save.png" width="30">
        </button>
        <button class="button" asp-page-handler="RefreshRobotSettingsFromRecipe" title="Load from database">
            <img src="~/icons/back.png" width="30">
        </button>
    </div>
</form>