Power X1 i-CT/Pages/Setup/MagazineLoader/SetupMagazineLoader.cshtml.cs
using MagazineLoader;
using MagazineLoader.Application;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Power_X1_iCT.Model;
using Power_X1_iCT.Resources;
using System.Threading.Tasks;

namespace Power_X1_iCT.Pages.Setup
{
    [BindProperties]
    public class SetupMagazineLoaderModel : PageModel
    {
        private readonly ILogger mLog;
        private readonly MagazineLoaderUpdater mUpdater;
        private MagazineLoaderModule mMagazineLoaderModule = MagazineLoaderModule.Instance;

        public MagazineLoaderSettingsModel MagazineLoaderSettingsModel { get; set; }

        public LoadMagazineSettingsModel LoadMagazineSettingsModel { get; set; }

        public ProvideMaterialSettingsModel ProvideMaterialSettingsModel { get; set; }

        public UnloadMagazineSettingsModel UnloadMagazineSettingsModel { get; set; }

        public bool SimulationEnabled { get; set; }

        public bool IsRunningProduction { get; set; }

        public SetupMagazineLoaderModel(MagazineLoaderUpdater magazineLoaderUpdater, ILogger<SetupMagazineLoaderModel> logger)
        {
            mLog = logger;
            mUpdater = magazineLoaderUpdater;
            MagazineLoaderSettingsModel = new MagazineLoaderSettingsModel();
            LoadMagazineSettingsModel = new LoadMagazineSettingsModel();
            ProvideMaterialSettingsModel = new ProvideMaterialSettingsModel();
            UnloadMagazineSettingsModel = new UnloadMagazineSettingsModel();
        }

        public JsonResult OnPostGetState()
        {
            return new JsonResult(new { state = StateBar.ConvertToString(mMagazineLoaderModule.State) });
        }

        public JsonResult OnPostGetStatusses()
        {
            return mUpdater.GetStatusses();
        }

        public JsonResult OnPostGetSimulationEnabled()
        {
            return new JsonResult(mMagazineLoaderModule.InSimulation);
        }

        public void OnPostInitialize()
        {
            mLog.LogInformation("OnInitialize");
            mMagazineLoaderModule.Initialize();
        }

        public void OnPostStart()
        {
            mMagazineLoaderModule.Start();
        }

        public void OnPostStop()
        {
            mMagazineLoaderModule.Stop();
        }

        public void OnPostLoadMagazine()
        {
            mMagazineLoaderModule.ExecuteLoadMagazine();
        }

        public void OnPostProvideMaterial()
        {
            mMagazineLoaderModule.ExecuteProvideMaterial();
        }

        public void OnPostUnloadMagazine()
        {
            mMagazineLoaderModule.ExecuteUnloadMagazine();
        }
        public void OnPostDownloadLoadMagazineSettingsToPLC(LoadMagazineSettingsModel model)
        {
            model.Download();
        }

        public IActionResult OnPostDownloadProvideMaterialSettingsToPLC()
        {
            ProvideMaterialSettingsModel.Download();

            // otherwise do some processing
            return RedirectToPage();
        }

        public void OnPostDownloadUnloadMagazineSettingsToPLC(UnloadMagazineSettingsModel model)
        {
            model.Download();
        }

        public void OnPostSaveLoadMagazineSettings()
        {
            LoadMagazineSettingsModel.Save();
        }
        public void OnPostSaveProvideMaterialSettings()
        {
            ProvideMaterialSettingsModel.Save();
        }

        public void OnPostSaveUnloadMagazineSettings()
        {
            UnloadMagazineSettingsModel.Save();
        }

        public IActionResult OnPostRefreshLoadMagazineSettingsFromRecipe()
        {
            // Should get last saved values from recipe

            return RedirectToPage();
        }

        public IActionResult OnPostRefreshProvideMaterialsSettingsFromRecipe()
        {
            // Should get last saved values from recipe

            return RedirectToPage();
        }

        public IActionResult OnPostRefreshUnloadMagazineSettingsFromRecipe()
        {
            // Should get last saved values from recipe

            return RedirectToPage();
        }

        public void OnPostSimulationChanged()
        {
            if (SimulationEnabled)
            {
                mMagazineLoaderModule.DisableSimulation();
            }
            else
            {
                mMagazineLoaderModule.EnableSimulation();
            }
        }

        public ActionResult OnPostSetVelocityPercentage(int percentage)
        {
            MagazineLoaderSettingsModel.SetVelocityPercentage(percentage);

            return new JsonResult("Succes");
        }
    }
}

Power X1 i-CT/Pages/Setup/MagazineLoader/Subprocesses/UnloadMagazine/UnloadMagazineSettingsPartial.cshtml
<form method="post">
    <button class="button" id="CloseSetupUnloadMagazine" title="Close settings" style="float:right; width:50px; height:50px">
        <img src="~/icons/close.png" style="width:35px; padding:1px" />
    </button>
</form>
<form method="post">
    <h2>Unload magazine settings</h2>
    <div>&nbsp;</div>
    <div class="settings-card settings">
        <div class="row">
            <label for="LowerConveyorZ" class="col-5">Lower conveyor Z</label>
            <input class="textbox" id="LowerConveyorZ" name="LowerConveyorZ" type="number" value="@Model.UnloadMagazineSettingsModel.LowerConveyorZ.ToString("F2")" min="1.00" max="125.00" step="0.10" />
            <label for="LowerConveyorZ">mm</label>
        </div>
        <div class="row">
            <label for="StartPlaceOffsetZ" class="col-5">Start place offset Z</label>
            <input class="textbox" id="StartPlaceOffsetZ" name="StartPlaceOffsetZ" type="number" value="@Model.UnloadMagazineSettingsModel.StartPlaceOffsetZ.ToString("F2")" min="1.00" max="25.00" step="1" />
            <label for="StartPlaceOffsetZ">mm</label>
        </div>
        <div class="row">
            <label for="PlaceY" class="col-5">Place Y</label>
            <input class="textbox" id="PlaceY" name="PlaceY" type="number" value="@Model.UnloadMagazineSettingsModel.PlaceY.ToString("F2")" min="1.00" max="225.00" step="0.1" />
            <label for="PlaceY">mm</label>
        </div>
        <div class="row">
            <label for="LiftSafePositionY" class="col-5">Lift safe position Y</label>
            <input class="textbox" id="LiftSafePositionY" name="LiftSafePositionY" type="number" value="@Model.UnloadMagazineSettingsModel.LiftSafePositionY.ToString("F2")" min="1.00" max="225.00" step="0.1" />
            <label for="LiftSafePositionY">mm</label>
        </div>
    </div>
    <div>&nbsp;</div>
    <div class="text-center">
        <button class="button" asp-page-handler="DownloadUnloadMagazineSettingsToPLC" title="Download to PLC">
            <img src="~/icons/download.png" width="30">
        </button>
        <button class="button" asp-page-handler="SaveUnloadMagazineSettings" title="Save to database">
            <img src="~/icons/save.png" width="30">
        </button>
        <button class="button" asp-page-handler="RefreshUnloadMagazineSettingsFromRecipe" title="Load from database">
            <img src="~/icons/back.png" width="30">
        </button>
    </div>
</form>